### ISSUE TITLE
Doorbell no longer working

### ISSUE THREAD

**Issue by CalvinGra** [ebaauw/homebridge-rpi#147]
Hello since the last update my doorbell device is no longer working and i get the following warning during startup:

```
[04/10/2022, 23:21:36] [RPi] warning: ignoring Raspberry Ingang: Cannot find module './GpioDoorBell'
Require stack:
- /usr/local/lib/node_modules/homebridge-rpi/lib/RpiService/GpioInput/index.js
- /usr/local/lib/node_modules/homebridge-rpi/lib/RpiService/index.js
- /usr/local/lib/node_modules/homebridge-rpi/lib/RpiAccessory/index.js
- /usr/local/lib/node_modules/homebridge-rpi/lib/RpiPlatform.js
- /usr/local/lib/node_modules/homebridge-rpi/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/childBridgeFork.js
[04/10/2022, 23:21:36] [RPi] Raspberry: warning: TypeError: Cannot read properties of undefined (reading 'init')
    at GpioAccessory.init (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiAccessory/GpioAccessory.js:26:25)
    at RpiAccessory.init (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiAccessory/index.js:111:41)
    at RpiPlatform.checkDevice (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiPlatform.js:364:26)
    at RpiPlatform.init (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiPlatform.js:192:7)
    at RpiPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiPlatform.js:16:46)
```

**Comment by ebaauw** [comment]
Damn typo in the filename.

**Comment by ebaauw** [comment]
Should work in beta v1.5.1-1.

**Comment by ebaauw** [comment]
Released v1.6.0.
